// Generated by CoffeeScript 1.3.3
(function() {

  require(['jquery'], function($) {
    window.eqfeed_callback = function(data) {
      return console.log(data);
    };
    $.ajax({
      url: 'http://earthquake.usgs.gov/earthquakes/feed/geojsonp/2.5/month',
      dataType: 'jsonp'
    });
    return $(function() {
      var svg;
      return svg = d3.get('body').append('svg');
    });
  });

}).call(this);
